app:
  producer:
    api:
      # http port to submit messages
      port: 9090
    replay:
      wakeup: 5s
  consumer:
    replay:
      batchSize: 10000
      wakeup: 5s

nats:
  server:
    clusterId: demo
  topics: ~

databases:
  postgres:
    default:
      #url: postgresql://postgres@localhost:5432/messagedb?sslmode=disable # <- local use
      url: postgresql://postgres@postgresql:5432/messagedb?sslmode=disable # <- local k8s
      user: $PG_USER
      password: $PG_PASSWORD
    pgconfig:
      log:
        level: warn

log:
  level: info

trace:
  enabled: false
