app:
  producer:
    api:
      # http port to submit messages
      port: 9090
    replay:
      wakeup: 5s
  consumer:
    replay:
      batchSize: 10000

nats:
  clusterId: local

databases:
  postgres:
    default:
      url: postgresql://postgres@localhost:5432/messagedb?sslmode=disable
    config:
      log:
        level: warn

log:
  level: info
