app:
  producer:
    api:
      # http port to submit messages
      port: 9090
    replay:
      wakeup: 5s
  consumer:
    replay:
      batchSize: 10000
      wakeup: 5s

nats:
  server:
    clusterId: demo
    clusterHeadlessService: daemon-nats-bank-cluster.default.svc.cluster.local  # <- NATS cluster discovery routes
    debug:
      logs: false # <- logs NAT embedded server
  topics: ~

databases:
  postgres:
    default:
      #url: postgresql://postgres@localhost:5432/messagedb?sslmode=disable # <- local use
      url: postgresql://daemon-postgresql.default.svc.cluster.local:5432/messagedb?sslmode=disable   # <- local k8s
      user: '$PG_USER'
      password: '$PG_PASSWORD'
  pgconfig: # <- default config for DB pool
    log:
      level: warn
    pingTimeout: 15s

log:
  level: debug

trace:
  enabled: false
